<?php
/**
 * VserverscheduledTaskApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RESELLING.SERVICES API
 *
 * Auf folgender Seite finden Sie die Beschreibung der RESELLING.SERVICES Schnittstelle  <!--<a href=\"https://reselling.services/api-docs?lang=en\" title=\"Englische Dokumentation\">Dokumentation in Englisch</a>-->
 *
 * OpenAPI spec version: 1.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * VserverscheduledTaskApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VserverscheduledTaskApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation vserverScheduledTaskCreate
     *
     * Geplante Aufgabe anlegen
     *
     * @param  int $server_id Server-ID (required)
     * @param  string $methode Aktion, welche ausgeführt werden soll. Mögliche Werte: start, stop, shutdown, restart, dump (required)
     * @param  string $interval Zeitintervall, wie die Aufgabe ausgeführt werden soll. Mögliche Werte: hourly, daily, 2-days, 3-days, 5-days, weekly, 2-weeks, monthly, yearly (required)
     * @param  string $next_execution_at Datum der ersten Ausführung. Dieses Datum muss in der Zukunft liegen. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ScheduledTask[]
     */
    public function vserverScheduledTaskCreate($server_id, $methode, $interval, $next_execution_at)
    {
        list($response) = $this->vserverScheduledTaskCreateWithHttpInfo($server_id, $methode, $interval, $next_execution_at);
        return $response;
    }

    /**
     * Operation vserverScheduledTaskCreateWithHttpInfo
     *
     * Geplante Aufgabe anlegen
     *
     * @param  int $server_id Server-ID (required)
     * @param  string $methode Aktion, welche ausgeführt werden soll. Mögliche Werte: start, stop, shutdown, restart, dump (required)
     * @param  string $interval Zeitintervall, wie die Aufgabe ausgeführt werden soll. Mögliche Werte: hourly, daily, 2-days, 3-days, 5-days, weekly, 2-weeks, monthly, yearly (required)
     * @param  string $next_execution_at Datum der ersten Ausführung. Dieses Datum muss in der Zukunft liegen. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ScheduledTask[], HTTP status code, HTTP response headers (array of strings)
     */
    public function vserverScheduledTaskCreateWithHttpInfo($server_id, $methode, $interval, $next_execution_at)
    {
        $returnType = '\Swagger\Client\Model\ScheduledTask[]';
        $request = $this->vserverScheduledTaskCreateRequest($server_id, $methode, $interval, $next_execution_at);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ScheduledTask[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation vserverScheduledTaskCreateAsync
     *
     * Geplante Aufgabe anlegen
     *
     * @param  int $server_id Server-ID (required)
     * @param  string $methode Aktion, welche ausgeführt werden soll. Mögliche Werte: start, stop, shutdown, restart, dump (required)
     * @param  string $interval Zeitintervall, wie die Aufgabe ausgeführt werden soll. Mögliche Werte: hourly, daily, 2-days, 3-days, 5-days, weekly, 2-weeks, monthly, yearly (required)
     * @param  string $next_execution_at Datum der ersten Ausführung. Dieses Datum muss in der Zukunft liegen. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function vserverScheduledTaskCreateAsync($server_id, $methode, $interval, $next_execution_at)
    {
        return $this->vserverScheduledTaskCreateAsyncWithHttpInfo($server_id, $methode, $interval, $next_execution_at)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation vserverScheduledTaskCreateAsyncWithHttpInfo
     *
     * Geplante Aufgabe anlegen
     *
     * @param  int $server_id Server-ID (required)
     * @param  string $methode Aktion, welche ausgeführt werden soll. Mögliche Werte: start, stop, shutdown, restart, dump (required)
     * @param  string $interval Zeitintervall, wie die Aufgabe ausgeführt werden soll. Mögliche Werte: hourly, daily, 2-days, 3-days, 5-days, weekly, 2-weeks, monthly, yearly (required)
     * @param  string $next_execution_at Datum der ersten Ausführung. Dieses Datum muss in der Zukunft liegen. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function vserverScheduledTaskCreateAsyncWithHttpInfo($server_id, $methode, $interval, $next_execution_at)
    {
        $returnType = '\Swagger\Client\Model\ScheduledTask[]';
        $request = $this->vserverScheduledTaskCreateRequest($server_id, $methode, $interval, $next_execution_at);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'vserverScheduledTaskCreate'
     *
     * @param  int $server_id Server-ID (required)
     * @param  string $methode Aktion, welche ausgeführt werden soll. Mögliche Werte: start, stop, shutdown, restart, dump (required)
     * @param  string $interval Zeitintervall, wie die Aufgabe ausgeführt werden soll. Mögliche Werte: hourly, daily, 2-days, 3-days, 5-days, weekly, 2-weeks, monthly, yearly (required)
     * @param  string $next_execution_at Datum der ersten Ausführung. Dieses Datum muss in der Zukunft liegen. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function vserverScheduledTaskCreateRequest($server_id, $methode, $interval, $next_execution_at)
    {
        // verify the required parameter 'server_id' is set
        if ($server_id === null || (is_array($server_id) && count($server_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server_id when calling vserverScheduledTaskCreate'
            );
        }
        // verify the required parameter 'methode' is set
        if ($methode === null || (is_array($methode) && count($methode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $methode when calling vserverScheduledTaskCreate'
            );
        }
        // verify the required parameter 'interval' is set
        if ($interval === null || (is_array($interval) && count($interval) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $interval when calling vserverScheduledTaskCreate'
            );
        }
        // verify the required parameter 'next_execution_at' is set
        if ($next_execution_at === null || (is_array($next_execution_at) && count($next_execution_at) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $next_execution_at when calling vserverScheduledTaskCreate'
            );
        }

        $resourcePath = '/vserver/scheduled_task/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($server_id !== null) {
            $queryParams['serverId'] = ObjectSerializer::toQueryValue($server_id, null);
        }
        // query params
        if ($methode !== null) {
            $queryParams['methode'] = ObjectSerializer::toQueryValue($methode, null);
        }
        // query params
        if ($interval !== null) {
            $queryParams['interval'] = ObjectSerializer::toQueryValue($interval, null);
        }
        // query params
        if ($next_execution_at !== null) {
            $queryParams['next_execution_at'] = ObjectSerializer::toQueryValue($next_execution_at, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation vserverScheduledTaskDelete
     *
     * Geplante Aufgabe löschen
     *
     * @param  int $server_id Server-ID (required)
     * @param  int $task_id Geplante Aufgaben ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ScheduledTask[]
     */
    public function vserverScheduledTaskDelete($server_id, $task_id)
    {
        list($response) = $this->vserverScheduledTaskDeleteWithHttpInfo($server_id, $task_id);
        return $response;
    }

    /**
     * Operation vserverScheduledTaskDeleteWithHttpInfo
     *
     * Geplante Aufgabe löschen
     *
     * @param  int $server_id Server-ID (required)
     * @param  int $task_id Geplante Aufgaben ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ScheduledTask[], HTTP status code, HTTP response headers (array of strings)
     */
    public function vserverScheduledTaskDeleteWithHttpInfo($server_id, $task_id)
    {
        $returnType = '\Swagger\Client\Model\ScheduledTask[]';
        $request = $this->vserverScheduledTaskDeleteRequest($server_id, $task_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ScheduledTask[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation vserverScheduledTaskDeleteAsync
     *
     * Geplante Aufgabe löschen
     *
     * @param  int $server_id Server-ID (required)
     * @param  int $task_id Geplante Aufgaben ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function vserverScheduledTaskDeleteAsync($server_id, $task_id)
    {
        return $this->vserverScheduledTaskDeleteAsyncWithHttpInfo($server_id, $task_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation vserverScheduledTaskDeleteAsyncWithHttpInfo
     *
     * Geplante Aufgabe löschen
     *
     * @param  int $server_id Server-ID (required)
     * @param  int $task_id Geplante Aufgaben ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function vserverScheduledTaskDeleteAsyncWithHttpInfo($server_id, $task_id)
    {
        $returnType = '\Swagger\Client\Model\ScheduledTask[]';
        $request = $this->vserverScheduledTaskDeleteRequest($server_id, $task_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'vserverScheduledTaskDelete'
     *
     * @param  int $server_id Server-ID (required)
     * @param  int $task_id Geplante Aufgaben ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function vserverScheduledTaskDeleteRequest($server_id, $task_id)
    {
        // verify the required parameter 'server_id' is set
        if ($server_id === null || (is_array($server_id) && count($server_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server_id when calling vserverScheduledTaskDelete'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling vserverScheduledTaskDelete'
            );
        }

        $resourcePath = '/vserver/scheduled_task/delete';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($server_id !== null) {
            $queryParams['serverId'] = ObjectSerializer::toQueryValue($server_id, null);
        }
        // query params
        if ($task_id !== null) {
            $queryParams['taskId'] = ObjectSerializer::toQueryValue($task_id, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation vserverScheduledTaskIndex
     *
     * vServer geplante Aufgabe abrufen
     *
     * @param  int $server_id Server-ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ScheduledTask[]
     */
    public function vserverScheduledTaskIndex($server_id)
    {
        list($response) = $this->vserverScheduledTaskIndexWithHttpInfo($server_id);
        return $response;
    }

    /**
     * Operation vserverScheduledTaskIndexWithHttpInfo
     *
     * vServer geplante Aufgabe abrufen
     *
     * @param  int $server_id Server-ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ScheduledTask[], HTTP status code, HTTP response headers (array of strings)
     */
    public function vserverScheduledTaskIndexWithHttpInfo($server_id)
    {
        $returnType = '\Swagger\Client\Model\ScheduledTask[]';
        $request = $this->vserverScheduledTaskIndexRequest($server_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ScheduledTask[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation vserverScheduledTaskIndexAsync
     *
     * vServer geplante Aufgabe abrufen
     *
     * @param  int $server_id Server-ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function vserverScheduledTaskIndexAsync($server_id)
    {
        return $this->vserverScheduledTaskIndexAsyncWithHttpInfo($server_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation vserverScheduledTaskIndexAsyncWithHttpInfo
     *
     * vServer geplante Aufgabe abrufen
     *
     * @param  int $server_id Server-ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function vserverScheduledTaskIndexAsyncWithHttpInfo($server_id)
    {
        $returnType = '\Swagger\Client\Model\ScheduledTask[]';
        $request = $this->vserverScheduledTaskIndexRequest($server_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'vserverScheduledTaskIndex'
     *
     * @param  int $server_id Server-ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function vserverScheduledTaskIndexRequest($server_id)
    {
        // verify the required parameter 'server_id' is set
        if ($server_id === null || (is_array($server_id) && count($server_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server_id when calling vserverScheduledTaskIndex'
            );
        }

        $resourcePath = '/vserver/scheduled_task';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($server_id !== null) {
            $queryParams['serverId'] = ObjectSerializer::toQueryValue($server_id, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
