<?php
/**
 * DomainTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RESELLING.SERVICES API
 *
 * Auf folgender Seite finden Sie die Beschreibung der RESELLING.SERVICES Schnittstelle  <!--<a href=\"https://reselling.services/api-docs?lang=en\" title=\"Englische Dokumentation\">Dokumentation in Englisch</a>-->
 *
 * OpenAPI spec version: 1.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DomainTest Class Doc Comment
 *
 * @category    Class
 * @description Domain
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Domain"
     */
    public function testDomain()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "sld"
     */
    public function testPropertySld()
    {
    }

    /**
     * Test attribute "tld"
     */
    public function testPropertyTld()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "name_unicode"
     */
    public function testPropertyNameUnicode()
    {
    }

    /**
     * Test attribute "owner_c"
     */
    public function testPropertyOwnerC()
    {
    }

    /**
     * Test attribute "admin_c"
     */
    public function testPropertyAdminC()
    {
    }

    /**
     * Test attribute "tech_c"
     */
    public function testPropertyTechC()
    {
    }

    /**
     * Test attribute "zone_c"
     */
    public function testPropertyZoneC()
    {
    }

    /**
     * Test attribute "create"
     */
    public function testPropertyCreate()
    {
    }

    /**
     * Test attribute "expire"
     */
    public function testPropertyExpire()
    {
    }

    /**
     * Test attribute "delete"
     */
    public function testPropertyDelete()
    {
    }

    /**
     * Test attribute "suspended_at"
     */
    public function testPropertySuspendedAt()
    {
    }

    /**
     * Test attribute "suspended_until"
     */
    public function testPropertySuspendedUntil()
    {
    }

    /**
     * Test attribute "authinfo"
     */
    public function testPropertyAuthinfo()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "zone_id"
     */
    public function testPropertyZoneId()
    {
    }

    /**
     * Test attribute "ns1"
     */
    public function testPropertyNs1()
    {
    }

    /**
     * Test attribute "ns2"
     */
    public function testPropertyNs2()
    {
    }

    /**
     * Test attribute "ns3"
     */
    public function testPropertyNs3()
    {
    }

    /**
     * Test attribute "ns4"
     */
    public function testPropertyNs4()
    {
    }

    /**
     * Test attribute "ns5"
     */
    public function testPropertyNs5()
    {
    }

    /**
     * Test attribute "premium_price_class"
     */
    public function testPropertyPremiumPriceClass()
    {
    }

    /**
     * Test attribute "verification_until"
     */
    public function testPropertyVerificationUntil()
    {
    }
}
