<?php
/**
 * PleskLicenseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  csakel\RUBClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RESELLING.SERVICES API
 *
 * Auf folgender Seite finden Sie die Beschreibung der RESELLING.SERVICES Schnittstelle  <!--<a href=\"https://reselling.services/api-docs?lang=en\" title=\"Englische Dokumentation\">Dokumentation in Englisch</a>-->
 *
 * OpenAPI spec version: 1.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace csakel\RUBClient;

use PHPUnit\Framework\TestCase;

/**
 * PleskLicenseTest Class Doc Comment
 *
 * @category    Class
 * @description PleskLicense
 * @package     csakel\RUBClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PleskLicenseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PleskLicense"
     */
    public function testPleskLicense()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "license"
     */
    public function testPropertyLicense()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "used"
     */
    public function testPropertyUsed()
    {
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "mac_address"
     */
    public function testPropertyMacAddress()
    {
    }

    /**
     * Test attribute "date_register"
     */
    public function testPropertyDateRegister()
    {
    }

    /**
     * Test attribute "date_update"
     */
    public function testPropertyDateUpdate()
    {
    }

    /**
     * Test attribute "expire"
     */
    public function testPropertyExpire()
    {
    }

    /**
     * Test attribute "orderdate"
     */
    public function testPropertyOrderdate()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "days"
     */
    public function testPropertyDays()
    {
    }

    /**
     * Test attribute "additional_keys"
     */
    public function testPropertyAdditionalKeys()
    {
    }

    /**
     * Test attribute "addons"
     */
    public function testPropertyAddons()
    {
    }
}
