<?php
/**
 * VserverNetworkInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  csakel\RUBClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RESELLING.SERVICES API
 *
 * Auf folgender Seite finden Sie die Beschreibung der RESELLING.SERVICES Schnittstelle  <!--<a href=\"https://reselling.services/api-docs?lang=en\" title=\"Englische Dokumentation\">Dokumentation in Englisch</a>-->
 *
 * OpenAPI spec version: 1.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace csakel\RUBClient;

use PHPUnit\Framework\TestCase;

/**
 * VserverNetworkInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description VserverNetworkInterface
 * @package     csakel\RUBClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VserverNetworkInterfaceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VserverNetworkInterface"
     */
    public function testVserverNetworkInterface()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "up"
     */
    public function testPropertyUp()
    {
    }

    /**
     * Test attribute "firewall"
     */
    public function testPropertyFirewall()
    {
    }

    /**
     * Test attribute "vlan_id"
     */
    public function testPropertyVlanId()
    {
    }

    /**
     * Test attribute "mac_address"
     */
    public function testPropertyMacAddress()
    {
    }

    /**
     * Test attribute "rate_limit"
     */
    public function testPropertyRateLimit()
    {
    }

    /**
     * Test attribute "bridge"
     */
    public function testPropertyBridge()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }
}
