<?php
/**
 * WebspaceUsageLimitsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  csakel\RUBClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RESELLING.SERVICES API
 *
 * Auf folgender Seite finden Sie die Beschreibung der RESELLING.SERVICES Schnittstelle  <!--<a href=\"https://reselling.services/api-docs?lang=en\" title=\"Englische Dokumentation\">Dokumentation in Englisch</a>-->
 *
 * OpenAPI spec version: 1.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace csakel\RUBClient;

use PHPUnit\Framework\TestCase;

/**
 * WebspaceUsageLimitsTest Class Doc Comment
 *
 * @category    Class
 * @description WebspaceUsageLimits
 * @package     csakel\RUBClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebspaceUsageLimitsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebspaceUsageLimits"
     */
    public function testWebspaceUsageLimits()
    {
    }

    /**
     * Test attribute "clients"
     */
    public function testPropertyClients()
    {
    }

    /**
     * Test attribute "domains"
     */
    public function testPropertyDomains()
    {
    }

    /**
     * Test attribute "subdomains"
     */
    public function testPropertySubdomains()
    {
    }

    /**
     * Test attribute "domain_aliases"
     */
    public function testPropertyDomainAliases()
    {
    }

    /**
     * Test attribute "disk_space"
     */
    public function testPropertyDiskSpace()
    {
    }

    /**
     * Test attribute "databases"
     */
    public function testPropertyDatabases()
    {
    }

    /**
     * Test attribute "mailboxes"
     */
    public function testPropertyMailboxes()
    {
    }

    /**
     * Test attribute "traffic"
     */
    public function testPropertyTraffic()
    {
    }
}
