<?php
/**
 * VservernetworkInterfaceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RESELLING.SERVICES API
 *
 * Auf folgender Seite finden Sie die Beschreibung der RESELLING.SERVICES Schnittstelle  <!--<a href=\"https://reselling.services/api-docs?lang=en\" title=\"Englische Dokumentation\">Dokumentation in Englisch</a>-->
 *
 * OpenAPI spec version: 1.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VservernetworkInterfaceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VservernetworkInterfaceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for vserverNetworkInterfaceDisable
     *
     * vServer Netzwerk Interface deaktivieren.
     *
     */
    public function testVserverNetworkInterfaceDisable()
    {
    }

    /**
     * Test case for vserverNetworkInterfaceEnable
     *
     * vServer Netzwerk Interface aktivieren.
     *
     */
    public function testVserverNetworkInterfaceEnable()
    {
    }

    /**
     * Test case for vserverNetworkInterfaceIndex
     *
     * vServer Netzwerk Interfaces abrufen.
     *
     */
    public function testVserverNetworkInterfaceIndex()
    {
    }

    /**
     * Test case for vserverNetworkInterfaceLimit
     *
     * vServer Netzwerk Interface limitieren.
     *
     */
    public function testVserverNetworkInterfaceLimit()
    {
    }

    /**
     * Test case for vserverNetworkInterfaceShow
     *
     * Einzelnes vServer Netzwerk Interface abrufen.
     *
     */
    public function testVserverNetworkInterfaceShow()
    {
    }
}
